# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 597652cce74cfcb2b11052d3c5a5b5d5fa408f6f13bf505ce3ad64ee5f5551191e1b0459b7a508dfb13fdddde427393506429e88acfd584b7c641c96e210354c

test:
  secret_key_base: 2a993569a48368101d875e100a2cc18ee871ca9a8b62884e284f5dde48b5b9c9c9266a12dfd570f5fd4491ec4de4c9f33a3acd78f94e863283729c579ebc43d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
